// This file is generated by Velite

export { default as articles } from './articles.json' with { type: 'json' }
export { default as perspectives } from './perspectives.json' with { type: 'json' }
export { default as projects } from './projects.json' with { type: 'json' }
export { default as docs } from './docs.json' with { type: 'json' }