// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Article = Collections['articles']['schema']['_output']
export declare const articles: Article[]

export type Perspective = Collections['perspectives']['schema']['_output']
export declare const perspectives: Perspective[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]
